services:
  localdb:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=sam0904
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=localdb

  testdb:
    image: postgres:15.1
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=sam0904
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=testdb
      