type Query {
    address: [Address]!
    users(input: PageInput!): UsersPayload!
    user(id: Int!): User!
    hello: String!
}

type Mutation {
    createUser(data: UserInput!): User!
    createAddress(data: AddressInput!): Address!
    login(data: LoginInput!): AuthPayload!
}

type User {
    id: ID!
    name: String!
    email: String!
    birthDate: String!
    addresses: [Address]
}

type Address {
    id: ID!
    cep: String!
    street: String!
    streetNumber: String!
    complement: String
    neighborhood: String!
    city: String!
    state: String!
}

type AuthPayload {
    user: User!
    token: String!
}

type UsersPayload {
    users: [User]!
    page: Int
    maxPage: Int
}

input PageInput {
    limit: Int = 10
    skip: Int = 0
}

input UserInput {
    name: String!
    email: String!
    password: String!
    birthDate: String!
}

input LoginInput {
    email: String!
    password: String!
    rememberMe: Boolean!
}

input AddressInput {
    userId: Int!
    cep: String!
    street: String!
    streetNumber: String!
    complement: String
    neighborhood: String!
    city: String!
    state: String!
}
