type Query{
    users(end: Int): [User],
    user(id: Int!): User,
    hello: String
}

type Mutation{
    createUser(data: UserInput!): User!,
    login(data: LoginInput!): AuthPayload!
}

type User{
    id: ID!
    name: String!
    email: String!
    birthDate: String!
}

type AuthPayload {
    user: User!
    token: String!
}

input UserInput{
    name: String!
    email: String!
    password: String!
    birthDate: String!
}

input LoginInput{
    email: String!
    password: String!
    rememberMe: Boolean!
}
